#this file was generated by chatgpt

# Pull and start pgvector image (detached)
docker run -d \
  --name regbrain-db \
  -e POSTGRES_USER=reguser \
  -e POSTGRES_PASSWORD=regpass \
  -e POSTGRES_DB=regbrain \
  -p 5432:5432 \
  ankane/pgvector